<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="C:\Projects\UnitTestProjects\UnitTestProjects\bin\Debug\UnitTestProjects.dll" total="2" errors="0" failures="1" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2016-09-20" time="12:51:18">
  <environment nunit-version="2.6.4.14350" clr-version="2.0.50727.8745" os-version="Microsoft Windows NT 6.2.9200.0" platform="Win32NT" cwd="c:\Tools\NUnit\bin" machine-name="DESKTOP-G1TV4KA" user="ilyaf" user-domain="DESKTOP-G1TV4KA" />
  <culture-info current-culture="en-US" current-uiculture="en-US" />
  <test-suite type="Assembly" name="C:\Projects\UnitTestProjects\UnitTestProjects\bin\Debug\UnitTestProjects.dll" executed="True" result="Failure" success="False" time="0.066" asserts="0">
    <results>
      <test-suite type="Namespace" name="UnitTestProjects" executed="True" result="Failure" success="False" time="0.057" asserts="0">
        <results>
          <test-suite type="TestFixture" name="NUnitTest1" executed="True" result="Failure" success="False" time="0.056" asserts="0">
            <results>
              <test-case name="UnitTestProjects.NUnitTest1.NunitTestMethod1" executed="True" result="Success" success="True" time="0.024" asserts="1" />
              <test-case name="UnitTestProjects.NUnitTest1.NunitTestMethod2" executed="True" result="Failure" success="False" time="0.013" asserts="1">
                <failure>
                  <message><![CDATA[  Expected: 1
  But was:  2
]]></message>
                  <stack-trace><![CDATA[at UnitTestProjects.NUnitTest1.NunitTestMethod2() in C:\Projects\UnitTestProjects\UnitTestProjects\NUnitTest1.cs:line 18
]]></stack-trace>
                </failure>
              </test-case>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>